// DO NOT EDIT THIS FILE
use crate::solver::Solver;

mod day01;
mod day02;

pub fn exec_day(day: i32) {
    match day {
        1 => day01::Problem {}.solve(day),
        2 => day02::Problem {}.solve(day),
        d => println!("Day {} hasn't been solved yet :(", d),
    }
}
